presets:
 - label: Disable
   name: disable
   general:
     enabled: False

 - label: Reset
   name: reset
   general:
     enabled: True
     transpositionExtra: False
   layers:
   - program: piano
     enabled: True
     active: True
     rangel: 0
     rangeu: 127
     transposition: 0
     pedals:
     - mode: none
     - mode: none
     - mode: none
     - mode: none
     - mode: none
     - mode: none
     - mode: none
     - mode: push_active

   - copy: {layer: 0}
     enabled: False
   - copy: {layer: 1}
   - copy: {layer: 1}
   - copy: {layer: 1}
   - copy: {layer: 1}
   - copy: {layer: 1}
   - copy: {layer: 1}

 - label: Piano
   name: piano
   layers:
   - program: piano

 - label: Piano + bass
   name: p_b
   general:
     transpositionExtra: True
   layers:
   - program: piano
     enabled: True
     active: True
     rangel: 60
     #rangel: 56
     rangeu: 127
   - program: bass
     enabled: True
     active: True
     rangel: 0
     rangeu: 59
     #rangeu: 55
   - program: piano
     enabled: True
     active: False
     rangel: 0
     rangeu: 127

 - label: Fretless bass
   name: fretless_bass
   layers:
   - layer: 1
     program: fretlessbass
